### ISSUE TITLE
Cannot run, says "gradle.vim requires python"

### ISSUE THREAD

**Issue by javster101** [aloussase/gradle.vim#1]
I am trying to run gradle.vim in Neovim, but it is saying on startup that it requires python. I have Python 3.9.7 available as `python` and `python3`. 

Changing the line `if !executable('python') || !has('python3')` to `if !executable('python') || !executable('python3')` in `plugin/gradle.vim` seems to partially fix it (it complains that there's no python3 runner, but does run the gradle command just fine). I'm not sure if its that way intentionally though.

**Comment by aloussase** [comment]
Hello, it should be fixed now. Python support is just needed if you want to be able to fetch dependencies from maven central (because I have not  found a way of doing http requests with lua from nvim yet). All other features should work fine without it. I will move the Python check to the function that actually uses Python.

By the way, if you are on a Debian based distro you can install Python support for  neovim with

```
sudo apt-get install python3-pynvim
``` 

Thanks for the feedback!
